"""association_table

Revision ID: 4d9f4f4bb26b
Revises: 1361bb572157
Create Date: 2023-03-23 15:36:10.056085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9f4f4bb26b'
down_revision = '1361bb572157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tag_association',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('Tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag_association')
    # ### end Alembic commands ###
